package com.dzx.ssm.model;

public class Goods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.id
     *
     * @mbggenerated Wed May 23 17:23:58 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.name
     *
     * @mbggenerated Wed May 23 17:23:58 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.price
     *
     * @mbggenerated Wed May 23 17:23:58 CST 2018
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.id
     *
     * @return the value of t_goods.id
     *
     * @mbggenerated Wed May 23 17:23:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.id
     *
     * @param id the value for t_goods.id
     *
     * @mbggenerated Wed May 23 17:23:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.name
     *
     * @return the value of t_goods.name
     *
     * @mbggenerated Wed May 23 17:23:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.name
     *
     * @param name the value for t_goods.name
     *
     * @mbggenerated Wed May 23 17:23:58 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.price
     *
     * @return the value of t_goods.price
     *
     * @mbggenerated Wed May 23 17:23:58 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.price
     *
     * @param price the value for t_goods.price
     *
     * @mbggenerated Wed May 23 17:23:58 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}